spring:
  application:
    name: TFA Spring Security
    security:
      jwt:
        secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
        expiration: 86400000 # a day
        refresh-token:
          expiration: 604800000 # 7 days
    web-url: "http://localhost:4200"
    qrcode-label: "2FA Example"
    qrcode-issuer: "afcruz"
  datasource:
    url: jdbc:mysql://localhost:3307/springTFA?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true